# Generated by Django 3.0.4 on 2020-03-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=300, null=True)),
                ('animal_type', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='shelters.Shelter')),
            ],
        ),
    ]
