# Generated by Django 3.0.4 on 2020-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_shelter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
