# Generated by Django 3.0.4 on 2020-03-19 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
        ('animals', '0003_animal_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='shelters.Shelter'),
        ),
    ]
