# Generated by Django 3.0.4 on 2020-03-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20200317_1938'),
        ('animals', '0003_animal_photo_url'),
    ]

    operations = [
    ]
