# Generated by Django 3.0.4 on 2020-03-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20200319_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='desctription',
            new_name='description',
        ),
    ]
