# Generated by Django 3.0.4 on 2020-03-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200315_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key',
            new_name='id',
        ),
    ]
