# Generated by Django 3.0.4 on 2020-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_favourite_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
