# Generated by Django 3.0.4 on 2020-03-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_url',
            new_name='photo_url',
        ),
    ]
